services:
  tailscale:
    image: tailscale/tailscale:latest
    env_file:
      - .env.tailscale
    container_name: tailscale-${SESSION_ID}
    hostname: tailscale-${SESSION_ID}                 # OS hostname inside the container
    environment:
      # EITHER: (recommended if your key is already Ephemeral+Preauth)
      - TS_AUTHKEY=${TS_AUTHKEY}              # no suffix
      # OR: if you mint a new preauthorized key you can use:
      # - TS_AUTHKEY=${TS_AUTHKEY}?ephemeral=true
      - TS_HOSTNAME=tailscale-${SESSION_ID}
      - TS_USERSPACE=false                      # <-- kernel/TUN mode
      - TS_ENABLE_HEALTH_CHECK=true             # built-in /healthz
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "tailscale ip -4 | grep -qE '^100\\.'"]
      interval: 5s
      timeout: 60s
      retries: 30
      start_period: 10s